version: "3.9"

services:
  server:
    build: .
    ports:
      - "8080:8080"
    links:
      - db
  db:
    image: "postgres"
    ports:
      - "5431:5432"
    environment:
      POSTGRES_PASSWORD: "1234"
      POSTGRES_USER: "postgres"
