version: "3.9"

services:
  server:
    build: .
    ports:
      - "7000:7000"
  db:
    image: "postgres"
    ports:
      - "5431:5432"
    environment:
      POSTGRES_PASSWORD: "mysecretpassword"
      POSTGRES_USER: "postgres"
